version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  apollo-graphql-server:
    container_name: graphql-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - postgres
    stdin_open: true
    image: bigfree:graphql-dev
    volumes:
      - ./:/graphqlapp
    command: yarn dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}